fxinterview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # http://localhost:8000/admin/
    url(r'^admin/', admin.site.urls),
    url(r'^application/', include('job_applications.urls')),
    url(r'^', include('main.urls')),
    url(r'^', include('registration.urls')),
]

handler400 = 'main.views.error_400'
handler401 = 'main.views.error_401'
handler403 = 'main.views.error_403'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

main/urls.py
from django.conf.urls import url, include

from . import views
from django.contrib.auth import views as auth_views

# name space for url
# e.g you can call {% url 'main.view_application_questions' xxx.id %} instead of hard code url in html

app_name = 'main'

urlpatterns = [
    # http://localhost:8000/
    url(r'^$', views.index, name='index'),
    # http://localhost:8000/accounts/home
    url(r'^accounts/home', views.check_user_role, name='view_home'),
    # http://localhost:8000/accounts/jobs
    url(r'^accounts/jobs', views.view_jobs, name='view_jobs'),
    # http://localhost:8000/accounts/create_job
    url(r'^accounts/create_job', views.create_job, name='create_job'),
    # http://localhost:8000/accounts/create_question
    url(r'^accounts/create_question', views.create_question, name='create_question'),
    # http://localhost:8000/accounts/edit_job
    url(r'^accounts/edit_job', views.edit_job, name='edit_job'),
    # http://localhost:8000/accounts/edit_question
    url(r'^accounts/edit_question', views.edit_question, name='edit_question'),
    # http://localhost:8000/accounts/delete_job
    url(r'^accounts/delete_job', views.delete_job, name='delete_job'),
    # http://localhost:8000/accounts/delete_question
    url(r'^accounts/delete_question', views.delete_question, name='delete_question'),
    # http://localhost:8000/accounts/questions
    url(r'^accounts/questions', views.view_questions, name='view_questions'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_profile', views.view_profile, name='view_profile'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_manage_interviewers', views.view_manage_interviewers, name='view_manage_interviewers'),
    # http://localhost:8000/accounts/update_profile
    url(r'^accounts/update_profile', views.update_profile, name='update_profile'),
    # http://localhost:8000/accounts/edit_interviewer
    url(r'^accounts/edit_interviewer', views.edit_interviewer, name='edit_interviewer'),
    # http://localhost:8000/accounts/send_job_invitation
    url(r'^accounts/send_job_invitation', views.send_job_invitation, name='send_job_invitation'),
    # http://localhost:8000/test_code
    url(r'^test_code', views.test_code, name='test_code'),

]

main/forms.py
from django import forms
from .models import Job, User, Profile, Question, QuestionType
from django.contrib.auth.forms import UserCreationForm


class JobForm(forms.ModelForm):
    name = forms.CharField(max_length=100, error_messages={'required': 'Job name is required',
                                                           'max_length': 'Job name is too long.'})
    description = forms.CharField(required=False)

    class Meta:
        model = Job
        fields = ('name', 'description', 'company')

    def clean(self):
        cleaned_data = super(JobForm, self).clean()
        name = cleaned_data.get('name')
        company = cleaned_data.get('company')

        if name and company and Job.objects.exclude(pk=self.instance.pk).filter(name=name, company=company).exists():
                raise forms.ValidationError({'name': ["Question name already exists", ]})

        return self.cleaned_data


class QuestionForm(forms.ModelForm):
    name = forms.CharField(max_length=100, error_messages={'required': 'Question name is required',
                                                           'max_length': 'Question name is too long.'})

    description = forms.CharField(required=False)

    default_template = forms.CharField(required=False)

    estimated_time_m = forms.IntegerField(required=False, error_messages={'required': 'ETC is required, default set to 0'})

    question_type = forms.ModelChoiceField(queryset=QuestionType.objects.all())

    class Meta:
        model = Question
        fields = ('name', 'description', 'company', 'default_template', 'estimated_time_m')

    def clean(self):
        cleaned_data = super(QuestionForm, self).clean()
        name = cleaned_data.get('name')
        company = cleaned_data.get('company')

        if name and company and Question.objects.exclude(pk=self.instance.pk).filter(name=name, company=company).exists():
            raise forms.ValidationError({'name': ["Question name already exists", ]})

        return self.cleaned_data


class FXUpdateUserForm(forms.ModelForm):
    username = forms.CharField(required=True, widget=forms.HiddenInput())
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def save(self, commit=True):
        user = super(FXUpdateUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user


class ProfileForm(forms.Form):
    first_name = forms.CharField(error_messages={'required': 'First Name is required'})
    last_name = forms.CharField(error_messages={'required': 'Last Name is required'})
    email = forms.CharField(error_messages={'required': 'Email is required'})
    role = forms.CharField(error_messages={'required': 'Role is required'})
    is_active = forms.CharField(error_messages={'required': 'Active is required'})

main/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import *
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from fx_tools.code_executor.fx_executor_factory import FXExecutorFactory
from fx_tools.utils import email_utils, fx_request_parameters, fx_string_utils
from fx_tools.utils import fx_constants
from job_applications.models import ApplicationQuestion
from registration.forms import FXCreateUserForm
from .forms import JobForm, QuestionForm, FXUpdateUserForm, ProfileForm
from .models import JobQuestion, Job, Question, Profile, User, QuestionType


def index(request):
    user_form = FXCreateUserForm(initial={'role': Profile.INTERVIEWEE_ROLE })
    # profile_form = ProfileForm(initial={'role': Profile.INTERVIEWEE_ROLE })

    return render(request, 'main/index.html', {'form': user_form, 'support_languages': fx_constants.SUPPORT_LANGUAGES})


@login_required(login_url='/login/')
def check_user_role(request):
    user = request.user
    if user is None or user.is_anonymous:
        return render(request, 'main/index.html')
    elif user.profile.is_interviewee():
        return interviewee_home(request)
    elif user.profile.is_interviewer():
        return __render_interviewer_admin_page(request, 'main/accounts/interviewer_home.html')
    elif user.profile.is_admin():
        return __render_interviewer_admin_page(request, 'main/accounts/admin_home.html')


@login_required(login_url='/login/')
def interviewee_home(request):
    user = request.user
    applications = ApplicationQuestion.objects.filter(interviewee_email=user.email)
    page = request.GET.get(fx_request_parameters.page)
    applications = __get_pagination_list(applications, page)
    return render(request, 'main/accounts/interviewee_home.html', {'applications': applications,
                                                                   'user': user,
                                                                   'page_range': applications.paginator.page_range})


def __render_interviewer_admin_page(request, url):
    user = request.user
    page = request.GET.get(fx_request_parameters.page)
    applications = []
    jobs = Job.objects.filter(company=user.profile.company)
    for job in jobs:
        applications.extend(ApplicationQuestion.objects.filter(job_id=job.id))

    applications = __get_pagination_list(applications, page)
    return render(request, url, {'applications': applications,
                                 'user': user,
                                 'page_range': applications.paginator.page_range})


def __get_pagination_list(original_list, page):
    paginator = Paginator(original_list, fx_constants.DEFAULT_PER_PAGE)
    try:
        pagination_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        pagination_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        pagination_list = paginator.page(paginator.num_pages)
    return pagination_list


@login_required(login_url='/login/')
def view_jobs(request):
    user = request.user
    jobs = Job.objects.filter(company=user.profile.company)
    page = request.GET.get(fx_request_parameters.page)
    jobs = __get_pagination_list(jobs, page)
    return render(request, 'main/accounts/view_jobs.html', {'jobs': jobs,
                                 'page_range': jobs.paginator.page_range})


@login_required(login_url='/login/')
def create_job(request):
    questions = Question.objects.all()
    if request.method == 'POST':
        create_job_form = JobForm(request.POST)
        if create_job_form.is_valid():
            job = create_job_form.save(commit=False)
            job.save()
            question_ids = request.POST.getlist('question_id')
            for question_id in question_ids:
                job_question = JobQuestion(job=job, question=Question.objects.get(pk=question_id))
                job_question.save()
            return HttpResponseRedirect(reverse('main:view_jobs'))
        else:
            return render(request, 'main/accounts/create_job.html', {'form': create_job_form, 'questions': questions})
    else:
        return render(request, 'main/accounts/create_job.html', {'questions': questions})


@login_required(login_url='/login/')
def create_question(request):
    question_types = QuestionType.objects.all()
    if request.method == 'POST':
        create_question_form = QuestionForm(request.POST)
        if create_question_form.is_valid():
            question = create_question_form.save(commit=False)
            question.save()
            return HttpResponseRedirect(reverse('main:view_questions'))
        else:
            return render(request, 'main/accounts/create_question.html', {'form': create_question_form, 'question_types': question_types})
    else:
        return render(request, 'main/accounts/create_question.html', {'question_types': question_types})


@login_required(login_url='/login/')
def edit_job(request):
    if request.method == 'POST':
        job = get_object_or_404(Job, pk=request.POST.get('id'))
        update_job_form = JobForm(request.POST, instance=job)
        if update_job_form.is_valid():
            job = update_job_form.save()
            question_ids = request.POST.getlist('question_id')
            JobQuestion.objects.filter(job=job).delete()
            for question_id in question_ids:
                job_question = JobQuestion(job=job, question=Question.objects.get(pk=question_id))
                job_question.save()
            return HttpResponseRedirect(reverse('main:view_jobs'))
        else:
            return __configure_edit_job(request, job=job, job_form=update_job_form)
    else:
        job = get_object_or_404(Job, pk=request.GET.get('id'))
        return __configure_edit_job(request, job=job)


@login_required(login_url='/login/')
def edit_question(request):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=request.POST.get('id'))
        update_question_form = QuestionForm(request.POST, instance=question)
        if update_question_form.is_valid():
            update_question_form.save()
            return HttpResponseRedirect(reverse('main:view_questions'))
        else:
            return __configure_edit_question(request, question=question, question_form=update_question_form)
    else:
        question = get_object_or_404(Question, pk=request.GET.get('id'))
        return __configure_edit_question(request, question=question)


def __configure_edit_job(request, job, job_form=None):
    job_questions = JobQuestion.objects.filter(job=job)
    assigned_questions = []
    temp_id = []
    for job_question in job_questions:
        question = get_object_or_404(Question, pk=job_question.question.id)
        assigned_questions.append(question)
        temp_id.append(question.id)
    questions = Question.objects.all().exclude(id__in=temp_id)
    return render(request, 'main/accounts/edit_job.html',
                  {'form': job_form, 'job': job, 'questions': questions, 'assigned_questions': assigned_questions})


def __configure_edit_question(request, question, question_form=None):
    question_types = QuestionType.objects.all()
    return render(request, 'main/accounts/edit_question.html',
                  {'form': question_form, 'question': question, 'question_types': question_types})


@login_required(login_url='/login/')
def delete_job(request):
    job = get_object_or_404(Job, pk=request.GET.get('id'))
    job.delete()
    return HttpResponseRedirect(reverse('main:view_jobs'))


@login_required(login_url='/login/')
def delete_question(request):
    question = get_object_or_404(Question, pk=request.GET.get('id'))
    question.delete()
    return HttpResponseRedirect(reverse('main:view_questions'))


@login_required(login_url='/login/')
def view_questions(request):
    user = request.user
    questions = Question.objects.filter(company=user.profile.company)
    page = request.GET.get(fx_request_parameters.page)
    questions = __get_pagination_list(questions, page)
    return render(request, 'main/accounts/view_questions.html', {'questions': questions,
                                                            'page_range': questions.paginator.page_range})


@login_required(login_url='/login/')
def view_profile(request):
    user = request.user
    form = FXUpdateUserForm()
    return __configure_profile(request, user, form)


@login_required(login_url='/login/')
def view_manage_interviewers(request):
    user = request.user
    interviewers = []
    if user.profile.is_admin():
        company = request.user.profile.company
        profiles = Profile.objects.filter(company=company)
        for profile in profiles:
            if user.username != profile.user.username:
                interviewers.append(profile.user)
    return render(request, 'main/accounts/view_manage_interviewers.html',
                  {'user': user, 'interviewers': interviewers})


@login_required(login_url='/login/')
def update_profile(request):
    user = request.user
    form = FXUpdateUserForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
    else:
        logging.info(form.errors)

    return __configure_profile(request, user, form)


@login_required(login_url='/login/')
def edit_interviewer(request):

    if request.method == 'POST':
        interviewer = get_object_or_404(User, pk=request.POST.get('id'))
        form = ProfileForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            interviewer.first_name = data['first_name']
            interviewer.last_name = data['last_name']
            interviewer.email = data['email']
            interviewer.profile.role = data['role']

            if data['is_active'] == 'True':

main/templates/main/accounts/create_job.html
{% extends "main/base.html" %}

{% block title %}Create New Job{% endblock %}

{% block content %}

    {% include "main/includes/form_error.html" %}

    <form method="post" data-toggle="validator" role="form" action="{% url 'main:create_job' %}">

        {% csrf_token %}

        <h3>Create Job</h3>

        <input type="hidden" name="company" value="{{ user.profile.company.id }}">

        <div class="form-group">
            <label for="job_name" class="control-label">Job Name</label>
            <input id="job_name" type="input" name="name" class="form-control" placeholder="Java Developer" required>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

        <div class="form-group input-container">
            <label for="job_description" class="control-label">Job Description</label>
            <textarea id="job_description" class="form-control" name="description" rows="12"></textarea>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

        <div class="form-group input-container">

            {% if questions %}

                <label>Select Questions:</label>

                <select id="jobSelect" class="form-control">

                    <option selected disabled>Select Questions</option>

                    {% for question in questions %}

                        <option value="{{ question.id }}">{{ question.name }}</option>

                    {% endfor %}

                </select>

            {% endif %}

        </div><!-- /.input-container -->

        <div class="form-group input-container">

            <label>Selected Questions:</label>

            <div id="selectedQuestionDiv" class="list-group"></div>

        </div><!-- /.input-container -->

        <input type="submit" class="btn btn-primary" value="Create">

    </form>

    {% load static %}
    <script src='{% static "main/js/create_job.js" %}' type="text/javascript" charset="utf-8"></script>
{% endblock %}

main/templates/main/accounts/create_question.html
{% extends "main/base.html" %}

{% block title %}Create New Question{% endblock %}

{% block content %}

    {% include "main/includes/form_error.html" %}

    <form method="post" data-toggle="validator" role="form" action="{% url 'main:create_question' %}">

        {% csrf_token %}

        <h3>Create Question</h3>

        <input type="hidden" name="company" value="{{ user.profile.company.id }}">

        <div class="form-group">
            <label for="question_name" class="control-label">Question Name</label>
            <input id="question_name" type="input" name="name" class="form-control" placeholder="Order ArrayList" required>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

         <div class="form-group input-container">
            <label for="job_description" class="control-label">Question Description</label>
            <textarea id="job_description" class="form-control" name="description" rows="12" required></textarea>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

        <div class="form-group input-container">

            <label for="comment">Default Template:</label>
            <textarea class="form-control" name="default_template" rows="10" id="comment">// Write your template here</textarea>

        </div><!-- /.input-container -->

         <div class="form-group input-container">
            <label for="question_type" class="control-label">Question Type</label>
                <select id="question_type" name="question_type" class="form-control">
                    {% for question_type in question_types %}
                         <option value="{{ question_type.type }}">{{ question_type.display_name }} | {{ question_type.description }}</option>
                    {% endfor %}
                </select>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

        <div class="form-group input-container">
            <label for="estimated_time" class="control-label">Estimated Time (Minute):</label>
            <input id="estimated_time" type="number" name="estimated_time_m" value="0"  min="0" step="1" class="form-control">
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->


        <input type="submit" class="btn btn-primary" value="Create">

    </form>

{% endblock %}

main/templates/main/accounts/edit_interviewer.html
{% extends "main/base.html" %}

{% block title %}Management{% endblock %}

{% block content %}

    {% include "main/includes/form_error.html" %}
    {% include "main/includes/alerts.html" %}

    <form method="post" data-toggle="validator" role="form" action="{% url 'main:edit_interviewer' %}">

        {% csrf_token %}

        <h3>Edit Interviewer</h3>

        <input type="hidden" name="id" value="{{ interviewer.id }}">

        <div class="form-group">
            <label for="username" class="control-label">Username</label>
            <input id="username" type="input" disabled class="form-control" placeholder="Username" value="{{ interviewer.username }}">
        </div><!-- /.input-container -->

        <div class="form-group">
            <label for="first_name" class="control-label">First Name</label>
            <input id="first_name" type="input" name="first_name" class="form-control" placeholder="Firstname" value="{{ interviewer.first_name }}" required>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

        <div class="form-group">
            <label for="last_name" class="control-label">Last Name</label>
            <input id="last_name" type="input" name="last_name" class="form-control" placeholder="Lastname" value="{{ interviewer.last_name }}" required>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

        <div class="form-group">
            <label for="email" class="control-label">Email</label>
            <input id="email" type="email" name="email" class="form-control" placeholder="Email Address" data-error="That email address is invalid" value="{{ interviewer.email }}" required>
            <div class="help-block with-errors"></div>
        </div><!-- /.input-container -->

         <div class="form-group">
             <label for="role" class="control-label">Role</label>
             <select id="role" name="role" class="form-control">
                 <option value="1">Admin</option>
                 <option value="2">Interviewer</option>
             </select>
        </div><!-- /.input-container -->

        <div class="form-group">
            <label for="is_active_checkbox" class="control-label">Active</label>
            <input id="is_active_checkbox" type="checkbox">
            <input id="hidden_is_active" name="is_active" value="False" type="hidden">
        </div><!-- /.input-container -->


        <input type="submit" class="btn btn-primary" value="Update">

    </form>

{% load static %}

<script type="text/javascript" >
    var interviewer_role = "{{ interviewer.profile.role|safe }}";
    var is_active = "{{ interviewer.is_active }}"
</script>
<script src='{% static "main/js/edit_interviewer.js" %}' type="text/javascript" charset="utf-8"></script>

{% endblock %}

main/templates/main/accounts/view_jobs.html
{% extends "main/base.html" %}

{% block title %}View Jobs{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header">
        <h3>Jobs
            <a href="{% url 'main:create_job' %}"><i class="fa fa-plus-square-o" aria-hidden="true"></i></a>
        </h3>
    </div>

    {% include "main/includes/alerts.html" %}

    {% if jobs %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <!--<th>Description</th>-->
                    <th>Updated</th>
                    <th>Question</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for job in jobs %}
                    <tr>
                        <td>{{ job.name }}</td>
                        <!--<td>{{ job.description }}</td>-->
                        <td>{{ job.updated|date:"Y-m-d H:i" }}</td>
                        <td>
                            <div class="btn-group">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Questions
                                    <span class="fa fa-caret-down" title="All related questions"></span>
                                </a>
                                <ul class="dropdown-menu">
                                     {% for question in job.get_questions %}
                                        <li>
                                        <a href="{% url 'main:edit_question'%}?id={{ question.id }}">
                                            {{ question.name }}
                                        </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </td>
                        <td>
                            <a href="{% url 'main:edit_job'%}?id={{ job.id }}" >
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <a href="{% url 'main:delete_job'%}?id={{ job.id }}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                            <a href="#" data-toggle="modal" data-target="#email_job_modal">
                                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            </a>
                            <input name="job_id" type="hidden" value="{{ job.id }}">
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    <!--
        <div class="list-group">
            {% for job in jobs %}
                <a href="{% url 'main:edit_job'%}?id={{ job.id }}"
                 class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between row">
                        <h5 class="col-md-6">{{ job.name }} - {{ job.updated|date:"DATE_FORMAT" }}</h5>

                        <small class="text-muted col-md-6 text-right">

                        </small>

                    </div>
                    <p class="mb-1">{{ job.description }}</p>


                </a>
                <small class="text-muted"><a href="{% url 'main:delete_job'%}?id={{ job.id }}">delete</a></small>
                <small class="text-muted"><a href="#" data-toggle="modal" data-target="#email_job_modal">email</a></small>
                <input name="job_id" type="hidden" value="{{ job.id }}">
            {% endfor %}
        </div>
        -->
    {% endif %}

    {% include "main/includes/pagination_div.html" with pagination_list=jobs page_range=page_range %}

    {% include "main/includes/email_job_modal.html" %}

    {% load static %}
    <script src='{% static "main/js/email_job_modal.js" %}' type="text/javascript" charset="utf-8"></script>
</div>
{% endblock %}

main/templates/main/accounts/view_manage_interviewers.html
{% extends "main/base.html" %}

{% block title %}Interviewers Management{% endblock %}

{% block content %}

{% include "main/includes/form_error.html" %}

<div class="page-header">
    <h3>Interviewers Management</h3>
</div>

{% if interviewers %}
 <div class="panel panel-default">
    <div class="panel-heading">
         <h3 class="panel-title">Manage Interviewers</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Activited</th>
                    <th>Last Login</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for interviewer in interviewers %}
                    <tr>
                        <td>{{ interviewer.username }}</td>
                        <td>{{ interviewer.email }}</td>
                        <td>
                            {% if interviewer.profile.role == 1 %}
                               Admin
                             {% else %}
                                Interviewer
                            {% endif %}
                        </td>
                        <td>
                             {% if interviewer.is_active %}
                               Yes
                             {% else %}
                               No
                            {% endif %}
                        </td>
                        <td>{{ interviewer.last_login |date:"Y-m-d H:i"}}</td>
                        <td>
                            <a href="{% url 'main:edit_interviewer'%}?id={{ interviewer.id }}">
                                <i class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i>
                             </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
 </div>

{% else %}

    <h3>No Interviewer Available</h3>

{% endif %}

{% load static %}
<script src='{% static "main/js/view_profile.js" %}' type="text/javascript" charset="utf-8"></script>
{% endblock %}

main/templates/main/accounts/view_questions.html
{% extends "main/base.html" %}

{% block title %}View Questions{% endblock %}

{% block content %}

<div class="container">
    <div class="page-header">
        <h3>
            Questions
            <a href="{% url 'main:create_question' %}"><i class="fa fa-plus-square-o" aria-hidden="true"></i></a>
        </h3>
    </div>

    {% if questions %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Question Type</th>
                    <th>ETC(Minute)</th>
                    <th>Updated</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for question in questions %}
                    <tr>
                        <td>{{ question.name }}</td>
                        <td class="ellipsis">{{ question.description }}</td>
                        <td>{{ question.question_type.display_name }}</td>
                        <td>{{ question.estimated_time_m }}</td>
                        <td>{{ question.updated|date:"Y-m-d H:i" }}</td>
                        <td>
                            <a href="{% url 'main:edit_question'%}?id={{ question.id }}">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                            <a href="{% url 'main:delete_question'%}?id={{ question.id }}">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% include "main/includes/pagination_div.html" with pagination_list=questions page_range=page_range %}
</div>

{% load static %}
<link rel="stylesheet" href='{% static "main/css/job.css" %}' type="text/css" />
{% endblock %}