fxinterview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # http://localhost:8000/admin/
    url(r'^admin/', admin.site.urls),
    url(r'^application/', include('job_applications.urls')),
    url(r'^', include('main.urls')),
    url(r'^', include('registration.urls')),
]

handler400 = 'main.views.error_400'
handler401 = 'main.views.error_401'
handler403 = 'main.views.error_403'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

main/urls.py
from django.conf.urls import url, include

from . import views
from django.contrib.auth import views as auth_views

# name space for url
# e.g you can call {% url 'main.view_application_questions' xxx.id %} instead of hard code url in html

app_name = 'main'

urlpatterns = [
    # http://localhost:8000/
    url(r'^$', views.index, name='index'),
    # http://localhost:8000/accounts/home
    url(r'^accounts/home', views.check_user_role, name='view_home'),
    # http://localhost:8000/accounts/jobs
    url(r'^accounts/jobs', views.view_jobs, name='view_jobs'),
    # http://localhost:8000/accounts/create_job
    url(r'^accounts/create_job', views.create_job, name='create_job'),
    # http://localhost:8000/accounts/create_question
    url(r'^accounts/create_question', views.create_question, name='create_question'),
    # http://localhost:8000/accounts/edit_job
    url(r'^accounts/edit_job', views.edit_job, name='edit_job'),
    # http://localhost:8000/accounts/edit_question
    url(r'^accounts/edit_question', views.edit_question, name='edit_question'),
    # http://localhost:8000/accounts/delete_job
    url(r'^accounts/delete_job', views.delete_job, name='delete_job'),
    # http://localhost:8000/accounts/delete_question
    url(r'^accounts/delete_question', views.delete_question, name='delete_question'),
    # http://localhost:8000/accounts/questions
    url(r'^accounts/questions', views.view_questions, name='view_questions'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_profile', views.view_profile, name='view_profile'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_manage_interviewers', views.view_manage_interviewers, name='view_manage_interviewers'),
    # http://localhost:8000/accounts/update_profile
    url(r'^accounts/update_profile', views.update_profile, name='update_profile'),
    # http://localhost:8000/accounts/edit_interviewer
    url(r'^accounts/edit_interviewer', views.edit_interviewer, name='edit_interviewer'),
    # http://localhost:8000/accounts/send_job_invitation
    url(r'^accounts/send_job_invitation', views.send_job_invitation, name='send_job_invitation'),
    # http://localhost:8000/test_code
    url(r'^test_code', views.test_code, name='test_code'),

]

main/forms.py
from django import forms
from .models import Job, User, Profile, Question, QuestionType
from django.contrib.auth.forms import UserCreationForm


class JobForm(forms.ModelForm):
    name = forms.CharField(max_length=100, error_messages={'required': 'Job name is required',
                                                           'max_length': 'Job name is too long.'})
    description = forms.CharField(required=False)

    class Meta:
        model = Job
        fields = ('name', 'description', 'company')

    def clean(self):
        cleaned_data = super(JobForm, self).clean()
        name = cleaned_data.get('name')
        company = cleaned_data.get('company')

        if name and company and Job.objects.exclude(pk=self.instance.pk).filter(name=name, company=company).exists():
                raise forms.ValidationError({'name': ["Question name already exists", ]})

        return self.cleaned_data


class QuestionForm(forms.ModelForm):
    name = forms.CharField(max_length=100, error_messages={'required': 'Question name is required',
                                                           'max_length': 'Question name is too long.'})

    description = forms.CharField(required=False)

    default_template = forms.CharField(required=False)

    estimated_time_m = forms.IntegerField(required=False, error_messages={'required': 'ETC is required, default set to 0'})

    question_type = forms.ModelChoiceField(queryset=QuestionType.objects.all())

    class Meta:
        model = Question
        fields = ('name', 'description', 'company', 'default_template', 'estimated_time_m')

    def clean(self):
        cleaned_data = super(QuestionForm, self).clean()
        name = cleaned_data.get('name')
        company = cleaned_data.get('company')

        if name and company and Question.objects.exclude(pk=self.instance.pk).filter(name=name, company=company).exists():
            raise forms.ValidationError({'name': ["Question name already exists", ]})

        return self.cleaned_data


class FXUpdateUserForm(forms.ModelForm):
    username = forms.CharField(required=True, widget=forms.HiddenInput())
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def save(self, commit=True):
        user = super(FXUpdateUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user


class ProfileForm(forms.Form):
    first_name = forms.CharField(error_messages={'required': 'First Name is required'})
    last_name = forms.CharField(error_messages={'required': 'Last Name is required'})
    email = forms.CharField(error_messages={'required': 'Email is required'})
    role = forms.CharField(error_messages={'required': 'Role is required'})
    is_active = forms.CharField(error_messages={'required': 'Active is required'})

main/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import *
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from fx_tools.code_executor.fx_executor_factory import FXExecutorFactory
from fx_tools.utils import email_utils, fx_request_parameters, fx_string_utils
from fx_tools.utils import fx_constants
from job_applications.models import ApplicationQuestion
from registration.forms import FXCreateUserForm
from .forms import JobForm, QuestionForm, FXUpdateUserForm, ProfileForm
from .models import JobQuestion, Job, Question, Profile, User, QuestionType


def index(request):
    user_form = FXCreateUserForm(initial={'role': Profile.INTERVIEWEE_ROLE })
    # profile_form = ProfileForm(initial={'role': Profile.INTERVIEWEE_ROLE })

    return render(request, 'main/index.html', {'form': user_form, 'support_languages': fx_constants.SUPPORT_LANGUAGES})


@login_required(login_url='/login/')
def check_user_role(request):
    user = request.user
    if user is None or user.is_anonymous:
        return render(request, 'main/index.html')
    elif user.profile.is_interviewee():
        return interviewee_home(request)
    elif user.profile.is_interviewer():
        return __render_interviewer_admin_page(request, 'main/accounts/interviewer_home.html')
    elif user.profile.is_admin():
        return __render_interviewer_admin_page(request, 'main/accounts/admin_home.html')


@login_required(login_url='/login/')
def interviewee_home(request):
    user = request.user
    applications = ApplicationQuestion.objects.filter(interviewee_email=user.email)
    page = request.GET.get(fx_request_parameters.page)
    applications = __get_pagination_list(applications, page)
    return render(request, 'main/accounts/interviewee_home.html', {'applications': applications,
                                                                   'user': user,
                                                                   'page_range': applications.paginator.page_range})


def __render_interviewer_admin_page(request, url):
    user = request.user
    page = request.GET.get(fx_request_parameters.page)
    applications = []
    jobs = Job.objects.filter(company=user.profile.company)
    for job in jobs:
        applications.extend(ApplicationQuestion.objects.filter(job_id=job.id))

    applications = __get_pagination_list(applications, page)
    return render(request, url, {'applications': applications,
                                 'user': user,
                                 'page_range': applications.paginator.page_range})


def __get_pagination_list(original_list, page):
    paginator = Paginator(original_list, fx_constants.DEFAULT_PER_PAGE)
    try:
        pagination_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        pagination_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        pagination_list = paginator.page(paginator.num_pages)
    return pagination_list


@login_required(login_url='/login/')
def view_jobs(request):
    user = request.user
    jobs = Job.objects.filter(company=user.profile.company)
    page = request.GET.get(fx_request_parameters.page)
    jobs = __get_pagination_list(jobs, page)
    return render(request, 'main/accounts/view_jobs.html', {'jobs': jobs,
                                 'page_range': jobs.paginator.page_range})


@login_required(login_url='/login/')
def create_job(request):
    questions = Question.objects.all()
    if request.method == 'POST':
        create_job_form = JobForm(request.POST)
        if create_job_form.is_valid():
            job = create_job_form.save(commit=False)
            job.save()
            question_ids = request.POST.getlist('question_id')
            for question_id in question_ids:
                job_question = JobQuestion(job=job, question=Question.objects.get(pk=question_id))
                job_question.save()
            return HttpResponseRedirect(reverse('main:view_jobs'))
        else:
            return render(request, 'main/accounts/create_job.html', {'form': create_job_form, 'questions': questions})
    else:
        return render(request, 'main/accounts/create_job.html', {'questions': questions})


@login_required(login_url='/login/')
def create_question(request):
    question_types = QuestionType.objects.all()
    if request.method == 'POST':
        create_question_form = QuestionForm(request.POST)
        if create_question_form.is_valid():
            question = create_question_form.save(commit=False)
            question.save()
            return HttpResponseRedirect(reverse('main:view_questions'))
        else:
            return render(request, 'main/accounts/create_question.html', {'form': create_question_form, 'question_types': question_types})
    else:
        return render(request, 'main/accounts/create_question.html', {'question_types': question_types})


@login_required(login_url='/login/')
def edit_job(request):
    if request.method == 'POST':
        job = get_object_or_404(Job, pk=request.POST.get('id'))
        update_job_form = JobForm(request.POST, instance=job)
        if update_job_form.is_valid():
            job = update_job_form.save()
            question_ids = request.POST.getlist('question_id')
            JobQuestion.objects.filter(job=job).delete()
            for question_id in question_ids:
                job_question = JobQuestion(job=job, question=Question.objects.get(pk=question_id))
                job_question.save()
            return HttpResponseRedirect(reverse('main:view_jobs'))
        else:
            return __configure_edit_job(request, job=job, job_form=update_job_form)
    else:
        job = get_object_or_404(Job, pk=request.GET.get('id'))
        return __configure_edit_job(request, job=job)


@login_required(login_url='/login/')
def edit_question(request):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=request.POST.get('id'))
        update_question_form = QuestionForm(request.POST, instance=question)
        if update_question_form.is_valid():
            update_question_form.save()
            return HttpResponseRedirect(reverse('main:view_questions'))
        else:
            return __configure_edit_question(request, question=question, question_form=update_question_form)
    else:
        question = get_object_or_404(Question, pk=request.GET.get('id'))
        return __configure_edit_question(request, question=question)


def __configure_edit_job(request, job, job_form=None):
    job_questions = JobQuestion.objects.filter(job=job)
    assigned_questions = []
    temp_id = []
    for job_question in job_questions:
        question = get_object_or_404(Question, pk=job_question.question.id)
        assigned_questions.append(question)
        temp_id.append(question.id)
    questions = Question.objects.all().exclude(id__in=temp_id)
    return render(request, 'main/accounts/edit_job.html',
                  {'form': job_form, 'job': job, 'questions': questions, 'assigned_questions': assigned_questions})


def __configure_edit_question(request, question, question_form=None):
    question_types = QuestionType.objects.all()
    return render(request, 'main/accounts/edit_question.html',
                  {'form': question_form, 'question': question, 'question_types': question_types})


@login_required(login_url='/login/')
def delete_job(request):
    job = get_object_or_404(Job, pk=request.GET.get('id'))
    job.delete()
    return HttpResponseRedirect(reverse('main:view_jobs'))


@login_required(login_url='/login/')
def delete_question(request):
    question = get_object_or_404(Question, pk=request.GET.get('id'))
    question.delete()
    return HttpResponseRedirect(reverse('main:view_questions'))


@login_required(login_url='/login/')
def view_questions(request):
    user = request.user
    questions = Question.objects.filter(company=user.profile.company)
    page = request.GET.get(fx_request_parameters.page)
    questions = __get_pagination_list(questions, page)
    return render(request, 'main/accounts/view_questions.html', {'questions': questions,
                                                            'page_range': questions.paginator.page_range})


@login_required(login_url='/login/')
def view_profile(request):
    user = request.user
    form = FXUpdateUserForm()
    return __configure_profile(request, user, form)


@login_required(login_url='/login/')
def view_manage_interviewers(request):
    user = request.user
    interviewers = []
    if user.profile.is_admin():
        company = request.user.profile.company
        profiles = Profile.objects.filter(company=company)
        for profile in profiles:
            if user.username != profile.user.username:
                interviewers.append(profile.user)
    return render(request, 'main/accounts/view_manage_interviewers.html',
                  {'user': user, 'interviewers': interviewers})


@login_required(login_url='/login/')
def update_profile(request):
    user = request.user
    form = FXUpdateUserForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
    else:
        logging.info(form.errors)

    return __configure_profile(request, user, form)


@login_required(login_url='/login/')
def edit_interviewer(request):

    if request.method == 'POST':
        interviewer = get_object_or_404(User, pk=request.POST.get('id'))
        form = ProfileForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            interviewer.first_name = data['first_name']
            interviewer.last_name = data['last_name']
            interviewer.email = data['email']
            interviewer.profile.role = data['role']

            if data['is_active'] == 'True':

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="stylesheet" href='{% static "main/css/main.css" %}' type="text/css" />

    <!--External links-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.9/validator.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <title>{% block title %}FX-Interview{% endblock %}</title>

    {% load i18n %}
</head>

<body>
    {% block sidebar %}
    <nav class="navbar navbar-default" id="topNav">

    <div class="container">

        <div class="container-fluid">

            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">

                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">123</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>

                <!--<div class="navbar-left">-->
                    <!--<img src= '{% static "main/images/" %}' alt="FXInterview.ie logo" />-->
                <!--</div>-->

                <a class="navbar-brand" href="">FXInterview</a>

            </div><!-- /.navbar-header -->

            <div id="navbar" class="navbar-collapse collapse">

                <ul class="nav navbar-nav navbar-right">

                    {% if user.is_authenticated %}

                        <li>
                            <a href="{% url 'main:view_home' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home</a>
                        </li>

                        {% if user.profile.is_admin or user.profile.is_interviewer %}

                            <li>
                                <a href="{% url 'main:view_jobs' %}"><i class="fa fa-bars" aria-hidden="true"></i> Jobs</a>
                            </li>

                            <li>
                                <a href="{% url 'main:view_questions' %}"><i class="fa fa-question-circle" aria-hidden="true"></i> Questions</a>
                            </li>

                        {% endif %}

                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                               {{ user.get_username }} <i class="fa fa-caret-down "></i>
                            </a>

                            <ul class="dropdown-menu">

                                <li>
                                    <a href="{% url 'main:view_profile' %}"><i class="fa fa-user fa-fw" aria-hidden="true"></i> Profile</a>
                                </li>

                                {% if user.profile.is_admin %}

                                    <li>
                                        <a href="{% url 'main:view_manage_interviewers' %}"><i class="fa fa-users fa-fw" aria-hidden="true"></i> Interviewers</a>
                                    </li>

                                {% endif %}

                                <li>
                                    <a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw" aria-hidden="true"></i> Logout</a>
                                </li>

                            </ul>

                        </li><!-- .dropdown -->

                    {% else %}

                        <li>
                            <a href="{% url 'main:index' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i> Home</a>
                        </li>

                        <li>
                            <a href="{% url 'login' %}"><i class="fa fa-sign-in fa-fw" aria-hidden="true"></i> Login</a>
                        </li>

                    {% endif %}

                    </ul>

                </div><!--/.nav-collapse -->

            </div><!--/.container-fluid -->

        </div><!-- /.container -->

    </nav>
    {% endblock %}

    <div id="content" class="container">
        {% block content %}{% endblock %}
    </div>

</body>
</html>

main/templates/main/index.html
{% extends "./base.html" %}
{% load i18n %}

{% block title %}{% trans 'FX-Interview' %}{% endblock %}

{% block content %}

<div class="row-fluid">
    <div class="col-xs-8 fx-div-left">
        <h3>{% trans 'Welcome to FX Interview' %}</h3>

        <form id="test_code_form" method="POST" action="{% url 'main:test_code' %}">
            {% csrf_token %}
            <input id="answer_content" name="answer_content" type="hidden" value="">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="panel-title">
                                <i class="fa fa-code" aria-hidden="true"></i>
                                <select id="selected_language" name="selected_language">
                                {% for support_language in support_languages %}
                                <option {% if support_language == selected_language %} selected {% endif %} value = {{ support_language }}>
                                    {{ support_language }}
                                </option>
                                {% endfor %}
                            </select>
                            </h3>
                        </div>
                    </div>
                </div>

                <div class="panel-body">
                    <div id="editor" ></div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                     <h3 class="panel-title">{% trans 'Output' %}</h3>
                </div>
                <div class="panel-body">
                    <p>{{ run_results.output }}</p>
                </div>
            </div>
            <div class="btn-group pull-right">
                <div class="btn-group">
                    <button type="submit" class="btn btn-primary" name="run_action" data-toggle="tooltip" title="Run">
                        <i class="fa fa-play" aria-hidden="true"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>

    <div class="col-xs-4 fx-div-right">
        <form data-toggle="validator" role="form" method="POST" action="{% url 'register' %}">
            {% csrf_token %}

            <h4>{% trans 'New Account' %}</h4>

            {% load widget_tweaks %}

            <div class="form-group">
                <div class="input-container input-group">
                     <span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
                    {% render_field form.username class="form-control" placeholder="Username" %}
                </div>
                <div class="help-block with-errors"></div>
            </div>

            <div class="form-group">
                <div class="input-container input-group">
                    <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                    {% render_field form.password1 class="form-control" placeholder="Password" %}
                </div>
                <div class="help-block with-errors"></div>
            </div>

            <div class="form-group">
                <div class="input-container input-group">
                    <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                    {% render_field form.password2 class="form-control" placeholder="Password Confirmation" %}
                </div>
                <div class="help-block with-errors"></div>
            </div>

            <div class="form-group">
                <div class="input-container input-group">
                    <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
                    {% render_field form.email class="form-control" placeholder="Email address" %}
                </div>
                <div class="help-block with-errors"></div>
            </div>

            {% render_field form.role %}

            <input type="submit" class="btn btn-primary" value="Sign Up">

        </form>
    </div>
</div>


{% load static %}
<script src='{% static "job_applications/ace-builds-master/src-noconflict/ace.js" %}' type="text/javascript" charset="utf-8"></script>
<script src='{% static "main/js/index.js" %}' type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href='{% static "main/css/index.css" %}' type="text/css" />

{% endblock %}