fxinterview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # http://localhost:8000/admin/
    url(r'^admin/', admin.site.urls),
    url(r'^application/', include('job_applications.urls')),
    url(r'^', include('main.urls')),
    url(r'^', include('registration.urls')),
]

handler400 = 'main.views.error_400'
handler401 = 'main.views.error_401'
handler403 = 'main.views.error_403'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

job_applications/urls.py
from django.conf.urls import url, include

from . import views
from django.contrib.auth import views as auth_views

# name space for url
# e.g you can call {% url 'main.view_application_questions' xxx.id %} instead of hard code url in html

app_name = 'job_applications'

urlpatterns = [
    # http://localhost:8000/application/2?interviewee_email=interviewee@fxinterview.com
    url(r'^application/(?P<application_question_id>[0-9]+)$', views.view_application_questions, name='view_application_questions'),
    # http://localhost:8000/application/start_answer$
    url(r'^application/start_answer', views.start_answer, name='start_answer'),
    # http://localhost:8000/application/submit_answer
    url(r'^application/submit_answer', views.submit_answer, name='submit_answer'),
    # http://localhost:8000/application/finish_answer
    url(r'^application/finish_answer', views.finish_answer, name='finish_answer'),
]

main/urls.py
from django.conf.urls import url, include

from . import views
from django.contrib.auth import views as auth_views

# name space for url
# e.g you can call {% url 'main.view_application_questions' xxx.id %} instead of hard code url in html

app_name = 'main'

urlpatterns = [
    # http://localhost:8000/
    url(r'^$', views.index, name='index'),
    # http://localhost:8000/accounts/home
    url(r'^accounts/home', views.check_user_role, name='view_home'),
    # http://localhost:8000/accounts/jobs
    url(r'^accounts/jobs', views.view_jobs, name='view_jobs'),
    # http://localhost:8000/accounts/create_job
    url(r'^accounts/create_job', views.create_job, name='create_job'),
    # http://localhost:8000/accounts/create_question
    url(r'^accounts/create_question', views.create_question, name='create_question'),
    # http://localhost:8000/accounts/edit_job
    url(r'^accounts/edit_job', views.edit_job, name='edit_job'),
    # http://localhost:8000/accounts/edit_question
    url(r'^accounts/edit_question', views.edit_question, name='edit_question'),
    # http://localhost:8000/accounts/delete_job
    url(r'^accounts/delete_job', views.delete_job, name='delete_job'),
    # http://localhost:8000/accounts/delete_question
    url(r'^accounts/delete_question', views.delete_question, name='delete_question'),
    # http://localhost:8000/accounts/questions
    url(r'^accounts/questions', views.view_questions, name='view_questions'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_profile', views.view_profile, name='view_profile'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_manage_interviewers', views.view_manage_interviewers, name='view_manage_interviewers'),
    # http://localhost:8000/accounts/update_profile
    url(r'^accounts/update_profile', views.update_profile, name='update_profile'),
    # http://localhost:8000/accounts/edit_interviewer
    url(r'^accounts/edit_interviewer', views.edit_interviewer, name='edit_interviewer'),
    # http://localhost:8000/accounts/send_job_invitation
    url(r'^accounts/send_job_invitation', views.send_job_invitation, name='send_job_invitation'),
    # http://localhost:8000/test_code
    url(r'^test_code', views.test_code, name='test_code'),

]

job_applications/models.py
import datetime

from django.db import models
from django.utils import timezone

from fx_tools.utils import fx_timezone_utils, fx_constants
from main.models import Job, JobQuestion


# Create your models here.


class ApplicationQuestion(models.Model):
    INIT = 1
    PENDING = 2
    DONE = 3
    STATUS = (
        (INIT, 'Init'),
        (PENDING, 'Pending'),
        (DONE, 'Done'),
    )

    interviewee_email = models.CharField(max_length=100)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    deadline = models.DateTimeField('Application deadline', null=True, blank=True)
    start_time = models.DateTimeField('Start answer time', null=True, blank=True)
    end_time = models.DateTimeField('End answer time', null=True, blank=True)
    estimated_time_m = models.IntegerField(default=0)  # this estimated time is based on questions' total estimated time
    status = models.IntegerField(choices=STATUS, default=INIT)
    created = models.DateTimeField('Application created time', auto_now_add=True, blank=True)

    class Meta:
        app_label = "job_applications"
        ordering = ('-created',)

    def get_estimated_end_time(self):
        estimated_end_time = None
        if self.start_time and self.estimated_time_m:
            estimated_end_time = timezone.localtime(self.start_time + datetime.timedelta(minutes=self.estimated_time_m))
        return estimated_end_time

    def is_expired(self):
        estimated_end_time = self.get_estimated_end_time()
        if estimated_end_time and estimated_end_time < fx_timezone_utils.get_local_time_now():
            return True
        return False

    def is_init(self):
        return self.status == self.INIT

    def is_finished(self):
        return self.status == self.DONE

    def start(self):
        self.start_time = fx_timezone_utils.get_local_time_now()
        self.status = ApplicationQuestion.PENDING
        self.save()

    def finish(self):
        self.end_time = fx_timezone_utils.get_local_time_now()
        self.status = ApplicationQuestion.DONE
        self.save()


class Answer(models.Model):
    application_question = models.ForeignKey(ApplicationQuestion, on_delete=models.CASCADE)
    job_question = models.ForeignKey(JobQuestion, on_delete=models.CASCADE)
    answer = models.TextField(null=True, blank=True)
    selected_language = models.TextField(null=False, blank=False, default=fx_constants.LANGUAGE_PYTHON)

    class Meta:
        app_label = "job_applications"
        unique_together = ('application_question', 'job_question',)

main/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import *
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from fx_tools.code_executor.fx_executor_factory import FXExecutorFactory
from fx_tools.utils import email_utils, fx_request_parameters, fx_string_utils
from fx_tools.utils import fx_constants
from job_applications.models import ApplicationQuestion
from registration.forms import FXCreateUserForm
from .forms import JobForm, QuestionForm, FXUpdateUserForm, ProfileForm
from .models import JobQuestion, Job, Question, Profile, User, QuestionType


def index(request):
    user_form = FXCreateUserForm(initial={'role': Profile.INTERVIEWEE_ROLE })
    # profile_form = ProfileForm(initial={'role': Profile.INTERVIEWEE_ROLE })

    return render(request, 'main/index.html', {'form': user_form, 'support_languages': fx_constants.SUPPORT_LANGUAGES})


@login_required(login_url='/login/')
def check_user_role(request):
    user = request.user
    if user is None or user.is_anonymous:
        return render(request, 'main/index.html')
    elif user.profile.is_interviewee():
        return interviewee_home(request)
    elif user.profile.is_interviewer():
        return __render_interviewer_admin_page(request, 'main/accounts/interviewer_home.html')
    elif user.profile.is_admin():
        return __render_interviewer_admin_page(request, 'main/accounts/admin_home.html')


@login_required(login_url='/login/')
def interviewee_home(request):
    user = request.user
    applications = ApplicationQuestion.objects.filter(interviewee_email=user.email)
    page = request.GET.get(fx_request_parameters.page)
    applications = __get_pagination_list(applications, page)
    return render(request, 'main/accounts/interviewee_home.html', {'applications': applications,
                                                                   'user': user,
                                                                   'page_range': applications.paginator.page_range})


def __render_interviewer_admin_page(request, url):
    user = request.user
    page = request.GET.get(fx_request_parameters.page)
    applications = []
    jobs = Job.objects.filter(company=user.profile.company)
    for job in jobs:
        applications.extend(ApplicationQuestion.objects.filter(job_id=job.id))

    applications = __get_pagination_list(applications, page)
    return render(request, url, {'applications': applications,
                                 'user': user,
                                 'page_range': applications.paginator.page_range})


def __get_pagination_list(original_list, page):
    paginator = Paginator(original_list, fx_constants.DEFAULT_PER_PAGE)
    try:
        pagination_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        pagination_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        pagination_list = paginator.page(paginator.num_pages)
    return pagination_list


@login_required(login_url='/login/')
def view_jobs(request):
    user = request.user
    jobs = Job.objects.filter(company=user.profile.company)
    page = request.GET.get(fx_request_parameters.page)
    jobs = __get_pagination_list(jobs, page)
    return render(request, 'main/accounts/view_jobs.html', {'jobs': jobs,
                                 'page_range': jobs.paginator.page_range})


@login_required(login_url='/login/')
def create_job(request):
    questions = Question.objects.all()
    if request.method == 'POST':
        create_job_form = JobForm(request.POST)
        if create_job_form.is_valid():
            job = create_job_form.save(commit=False)
            job.save()
            question_ids = request.POST.getlist('question_id')
            for question_id in question_ids:
                job_question = JobQuestion(job=job, question=Question.objects.get(pk=question_id))
                job_question.save()
            return HttpResponseRedirect(reverse('main:view_jobs'))
        else:
            return render(request, 'main/accounts/create_job.html', {'form': create_job_form, 'questions': questions})
    else:
        return render(request, 'main/accounts/create_job.html', {'questions': questions})


@login_required(login_url='/login/')
def create_question(request):
    question_types = QuestionType.objects.all()
    if request.method == 'POST':
        create_question_form = QuestionForm(request.POST)
        if create_question_form.is_valid():
            question = create_question_form.save(commit=False)
            question.save()
            return HttpResponseRedirect(reverse('main:view_questions'))
        else:
            return render(request, 'main/accounts/create_question.html', {'form': create_question_form, 'question_types': question_types})
    else:
        return render(request, 'main/accounts/create_question.html', {'question_types': question_types})


@login_required(login_url='/login/')
def edit_job(request):
    if request.method == 'POST':
        job = get_object_or_404(Job, pk=request.POST.get('id'))
        update_job_form = JobForm(request.POST, instance=job)
        if update_job_form.is_valid():
            job = update_job_form.save()
            question_ids = request.POST.getlist('question_id')
            JobQuestion.objects.filter(job=job).delete()
            for question_id in question_ids:
                job_question = JobQuestion(job=job, question=Question.objects.get(pk=question_id))
                job_question.save()
            return HttpResponseRedirect(reverse('main:view_jobs'))
        else:
            return __configure_edit_job(request, job=job, job_form=update_job_form)
    else:
        job = get_object_or_404(Job, pk=request.GET.get('id'))
        return __configure_edit_job(request, job=job)


@login_required(login_url='/login/')
def edit_question(request):
    if request.method == 'POST':
        question = get_object_or_404(Question, pk=request.POST.get('id'))
        update_question_form = QuestionForm(request.POST, instance=question)
        if update_question_form.is_valid():
            update_question_form.save()
            return HttpResponseRedirect(reverse('main:view_questions'))
        else:
            return __configure_edit_question(request, question=question, question_form=update_question_form)
    else:
        question = get_object_or_404(Question, pk=request.GET.get('id'))
        return __configure_edit_question(request, question=question)


def __configure_edit_job(request, job, job_form=None):
    job_questions = JobQuestion.objects.filter(job=job)
    assigned_questions = []
    temp_id = []
    for job_question in job_questions:
        question = get_object_or_404(Question, pk=job_question.question.id)
        assigned_questions.append(question)
        temp_id.append(question.id)
    questions = Question.objects.all().exclude(id__in=temp_id)
    return render(request, 'main/accounts/edit_job.html',
                  {'form': job_form, 'job': job, 'questions': questions, 'assigned_questions': assigned_questions})


def __configure_edit_question(request, question, question_form=None):
    question_types = QuestionType.objects.all()
    return render(request, 'main/accounts/edit_question.html',
                  {'form': question_form, 'question': question, 'question_types': question_types})


@login_required(login_url='/login/')
def delete_job(request):
    job = get_object_or_404(Job, pk=request.GET.get('id'))
    job.delete()
    return HttpResponseRedirect(reverse('main:view_jobs'))


@login_required(login_url='/login/')
def delete_question(request):
    question = get_object_or_404(Question, pk=request.GET.get('id'))
    question.delete()
    return HttpResponseRedirect(reverse('main:view_questions'))


@login_required(login_url='/login/')
def view_questions(request):
    user = request.user
    questions = Question.objects.filter(company=user.profile.company)
    page = request.GET.get(fx_request_parameters.page)
    questions = __get_pagination_list(questions, page)
    return render(request, 'main/accounts/view_questions.html', {'questions': questions,
                                                            'page_range': questions.paginator.page_range})


@login_required(login_url='/login/')
def view_profile(request):
    user = request.user
    form = FXUpdateUserForm()
    return __configure_profile(request, user, form)


@login_required(login_url='/login/')
def view_manage_interviewers(request):
    user = request.user
    interviewers = []
    if user.profile.is_admin():
        company = request.user.profile.company
        profiles = Profile.objects.filter(company=company)
        for profile in profiles:
            if user.username != profile.user.username:
                interviewers.append(profile.user)
    return render(request, 'main/accounts/view_manage_interviewers.html',
                  {'user': user, 'interviewers': interviewers})


@login_required(login_url='/login/')
def update_profile(request):
    user = request.user
    form = FXUpdateUserForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
    else:
        logging.info(form.errors)

    return __configure_profile(request, user, form)


@login_required(login_url='/login/')
def edit_interviewer(request):

    if request.method == 'POST':
        interviewer = get_object_or_404(User, pk=request.POST.get('id'))
        form = ProfileForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            interviewer.first_name = data['first_name']
            interviewer.last_name = data['last_name']
            interviewer.email = data['email']
            interviewer.profile.role = data['role']

            if data['is_active'] == 'True':

main/templates/main/includes/alerts.html
{% if success_message %}
    <div class="alert alert-success">
      <strong>Success!</strong> {{ success_message }}
    </div>
{% endif %}

{% if info_message %}
    <div class="alert alert-info">
      <strong>Info!</strong> {{ info_message }}
    </div>
{% endif %}

{% if warning_message %}
    <div class="alert alert-warning">
      <strong>Warning!</strong> {{ warning_message }}
    </div>
{% endif %}

{% if danger_message %}
    <div class="alert alert-danger">
      <strong>Danger!</strong> {{ danger_message }}
    </div>
{% endif %}

main/templates/main/includes/application_list.html
{% if applications %}
    <div class="list-group">
        {% for application in applications %}
            <a href="{% url 'job_applications:view_application_questions' application_question_id=application.id %}?interviewee_email={{ application.interviewee_email }}"
             class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between row">
                    <h5 class="col-md-6">{{ application.job.name }} - {{ application.created|date:"DATE_FORMAT" }}</h5>

                    <small class="text-muted col-md-6 text-right">
                        {% if user.profile.is_interviewee %}
                            Required finish in {{ application.estimated_time_m }} minutes
                        {% else %}
                            {{ application.interviewee_email }}
                        {% endif %}
                    </small>

                </div>
                <!--<p class="mb-1">{{ application.job.description }}</p>-->
                {% if application.deadline %}
                <small class="text-muted">Expected finished before {{ application.deadline|date:"DATE_FORMAT" }}</small>
                {% endif %}
                {% if not user.profile.is_interviewee %}
                <small class="text-muted">Status - {{ application.get_status_display }}</small>
                {% endif %}
            </a>
        {% endfor %}
    </div>
{% endif %}

{% include "main/includes/pagination_div.html" with pagination_list=applications page_range=page_range %}

main/templates/main/includes/email_job_modal.html
<div id="email_job_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Job Invitation </h4>
        </div>
        <div class="modal-body">
            <form id="job_invitation_form" data-toggle="validator" role="form" method="post" action="{% url 'main:send_job_invitation' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="interviewee_email" class="control-label">Send Job Invitation Email to:</label>
                    <input id="interviewee_email" type="email" name="interviewee_email" class="form-control" placeholder="xxx@fxinterview.ie" required>
                    <div class="help-block with-errors"></div>
                </div><!-- /.input-container -->

                  <div class="form-group">
                    <label for="datepicker" class="control-label">Expire Date(Optional):</label>
                    <input name="expire_date" type="text" class="form-control" id="datepicker">
                    <div class="help-block with-errors"></div>
                </div><!-- /.input-container -->

                <input id="email_job_id" name="email_job_id" type="hidden">
            </form>
        </div>
        <div class="modal-footer">
            <button id="send_btn" type="button" class="btn btn-default">Send</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
  </div>
</div>

main/templates/main/includes/form_error.html
{% if form.errors %}

    {% for field in form %}

        {% for error in field.errors %}

            <div class="alert alert-danger">

                 <i class="fa fa-exclamation-triangle"></i>

                <strong>{{ error|escape }}</strong>

            </div>

        {% endfor %}

    {% endfor %}

{% endif %}

main/templates/main/includes/pagination_div.html
<!--
<div class="pagination">
    <span class="step-links">
        {% if pagination_list.has_previous %}
            <a href="?page={{ pagination_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ pagination_list.number }} of {{ pagination_list.paginator.num_pages }}.
        </span>

        {% if pagination_list.has_next %}
            <a href="?page={{ pagination_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
-->
<div>
    <ul class="pagination">
        {% for i in page_range %}
          <li {% if pagination_list.number == i %}class="disabled"{% endif %}><a href="?page={{ i }}">{{i}}</a></li>
        {% endfor %}
    </ul>
</div>