fxinterview/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    # http://localhost:8000/admin/
    url(r'^admin/', admin.site.urls),
    url(r'^application/', include('job_applications.urls')),
    url(r'^', include('main.urls')),
    url(r'^', include('registration.urls')),
]

handler400 = 'main.views.error_400'
handler401 = 'main.views.error_401'
handler403 = 'main.views.error_403'
handler404 = 'main.views.error_404'
handler500 = 'main.views.error_500'

job_applications/urls.py
from django.conf.urls import url, include

from . import views
from django.contrib.auth import views as auth_views

# name space for url
# e.g you can call {% url 'main.view_application_questions' xxx.id %} instead of hard code url in html

app_name = 'job_applications'

urlpatterns = [
    # http://localhost:8000/application/2?interviewee_email=interviewee@fxinterview.com
    url(r'^application/(?P<application_question_id>[0-9]+)$', views.view_application_questions, name='view_application_questions'),
    # http://localhost:8000/application/start_answer$
    url(r'^application/start_answer', views.start_answer, name='start_answer'),
    # http://localhost:8000/application/submit_answer
    url(r'^application/submit_answer', views.submit_answer, name='submit_answer'),
    # http://localhost:8000/application/finish_answer
    url(r'^application/finish_answer', views.finish_answer, name='finish_answer'),
]

main/urls.py
from django.conf.urls import url, include

from . import views
from django.contrib.auth import views as auth_views

# name space for url
# e.g you can call {% url 'main.view_application_questions' xxx.id %} instead of hard code url in html

app_name = 'main'

urlpatterns = [
    # http://localhost:8000/
    url(r'^$', views.index, name='index'),
    # http://localhost:8000/accounts/home
    url(r'^accounts/home', views.check_user_role, name='view_home'),
    # http://localhost:8000/accounts/jobs
    url(r'^accounts/jobs', views.view_jobs, name='view_jobs'),
    # http://localhost:8000/accounts/create_job
    url(r'^accounts/create_job', views.create_job, name='create_job'),
    # http://localhost:8000/accounts/create_question
    url(r'^accounts/create_question', views.create_question, name='create_question'),
    # http://localhost:8000/accounts/edit_job
    url(r'^accounts/edit_job', views.edit_job, name='edit_job'),
    # http://localhost:8000/accounts/edit_question
    url(r'^accounts/edit_question', views.edit_question, name='edit_question'),
    # http://localhost:8000/accounts/delete_job
    url(r'^accounts/delete_job', views.delete_job, name='delete_job'),
    # http://localhost:8000/accounts/delete_question
    url(r'^accounts/delete_question', views.delete_question, name='delete_question'),
    # http://localhost:8000/accounts/questions
    url(r'^accounts/questions', views.view_questions, name='view_questions'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_profile', views.view_profile, name='view_profile'),
    # http://localhost:8000/accounts/view_profile
    url(r'^accounts/view_manage_interviewers', views.view_manage_interviewers, name='view_manage_interviewers'),
    # http://localhost:8000/accounts/update_profile
    url(r'^accounts/update_profile', views.update_profile, name='update_profile'),
    # http://localhost:8000/accounts/edit_interviewer
    url(r'^accounts/edit_interviewer', views.edit_interviewer, name='edit_interviewer'),
    # http://localhost:8000/accounts/send_job_invitation
    url(r'^accounts/send_job_invitation', views.send_job_invitation, name='send_job_invitation'),
    # http://localhost:8000/test_code
    url(r'^test_code', views.test_code, name='test_code'),

]

job_applications/models.py
import datetime

from django.db import models
from django.utils import timezone

from fx_tools.utils import fx_timezone_utils, fx_constants
from main.models import Job, JobQuestion


# Create your models here.


class ApplicationQuestion(models.Model):
    INIT = 1
    PENDING = 2
    DONE = 3
    STATUS = (
        (INIT, 'Init'),
        (PENDING, 'Pending'),
        (DONE, 'Done'),
    )

    interviewee_email = models.CharField(max_length=100)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    deadline = models.DateTimeField('Application deadline', null=True, blank=True)
    start_time = models.DateTimeField('Start answer time', null=True, blank=True)
    end_time = models.DateTimeField('End answer time', null=True, blank=True)
    estimated_time_m = models.IntegerField(default=0)  # this estimated time is based on questions' total estimated time
    status = models.IntegerField(choices=STATUS, default=INIT)
    created = models.DateTimeField('Application created time', auto_now_add=True, blank=True)

    class Meta:
        app_label = "job_applications"
        ordering = ('-created',)

    def get_estimated_end_time(self):
        estimated_end_time = None
        if self.start_time and self.estimated_time_m:
            estimated_end_time = timezone.localtime(self.start_time + datetime.timedelta(minutes=self.estimated_time_m))
        return estimated_end_time

    def is_expired(self):
        estimated_end_time = self.get_estimated_end_time()
        if estimated_end_time and estimated_end_time < fx_timezone_utils.get_local_time_now():
            return True
        return False

    def is_init(self):
        return self.status == self.INIT

    def is_finished(self):
        return self.status == self.DONE

    def start(self):
        self.start_time = fx_timezone_utils.get_local_time_now()
        self.status = ApplicationQuestion.PENDING
        self.save()

    def finish(self):
        self.end_time = fx_timezone_utils.get_local_time_now()
        self.status = ApplicationQuestion.DONE
        self.save()


class Answer(models.Model):
    application_question = models.ForeignKey(ApplicationQuestion, on_delete=models.CASCADE)
    job_question = models.ForeignKey(JobQuestion, on_delete=models.CASCADE)
    answer = models.TextField(null=True, blank=True)
    selected_language = models.TextField(null=False, blank=False, default=fx_constants.LANGUAGE_PYTHON)

    class Meta:
        app_label = "job_applications"
        unique_together = ('application_question', 'job_question',)

job_applications/views.py
import logging

from django.shortcuts import render, get_object_or_404, get_list_or_404

from fx_tools.code_executor.fx_executor_factory import FXExecutorFactory
from fx_tools.utils import fx_constants, fx_string_utils
from .models import ApplicationQuestion, JobQuestion, Answer


# Create your views here.


def view_application_questions(request, application_question_id):
    interviewee_email = request.GET.get('interviewee_email')
    if interviewee_email is None:
        interviewee_email = request.POST.get('interviewee_email')
    logging.info(str(interviewee_email) + " is viewing application question with id " + str(application_question_id))
    application_question = get_object_or_404(ApplicationQuestion, pk=application_question_id, interviewee_email=interviewee_email)

    if application_question.start_time:
        job_questions = get_list_or_404(JobQuestion, job=application_question.job)
        job_question = job_questions[0]
        answer = Answer.objects.filter(application_question=application_question, job_question=job_question).first()
        # show the initial question at the first time
        estimated_end_time = fx_string_utils.format_date_b_d_y_h_m_s(application_question.get_estimated_end_time())
        return render(request, 'job_applications/view_application_questions.html',
                      {'application_question': application_question,
                       'job_question': job_question,
                       'interviewee_email': interviewee_email,
                       'estimated_end_time': estimated_end_time,
                       'answer': answer,
                       'support_languages': fx_constants.SUPPORT_LANGUAGES})
    else:
        # show welcome page
        return render(request, 'job_applications/welcome.html',
                      {'application_question': application_question,
                       'interviewee_email': interviewee_email})


def start_answer(request):
    interviewee_email = request.POST.get('interviewee_email')
    application_question_id = request.POST.get('application_question_id')
    application_question = get_object_or_404(ApplicationQuestion, pk=application_question_id, interviewee_email=interviewee_email)
    if application_question.is_init():
        application_question.start()

    job_questions = get_list_or_404(JobQuestion, job=application_question.job)

    # show the initial question at the first time
    estimated_end_time = fx_string_utils.format_date_b_d_y_h_m_s(application_question.get_estimated_end_time())
    return render(request, 'job_applications/view_application_questions.html', {'application_question': application_question,
                                                                    'job_question': job_questions[0],
                                                                    'interviewee_email': interviewee_email,
                                                                    'estimated_end_time': estimated_end_time,
                                                                    'support_languages': fx_constants.SUPPORT_LANGUAGES})


def submit_answer(request):
    interviewee_email = request.POST.get('interviewee_email')
    application_question_id = request.POST.get('application_question_id')
    job_question_id = request.POST.get('job_question_id')
    answer_content = request.POST.get('answer_content')
    selected_language = request.POST.get('selected_language')
    submit_action = request.POST.get('submit_action')
    prev_action = request.POST.get('prev_action')
    next_action = request.POST.get('next_action')
    run_action = request.POST.get('run_action')

    application_question = get_object_or_404(ApplicationQuestion, pk=application_question_id, interviewee_email=interviewee_email)
    job_question = get_object_or_404(JobQuestion, pk=job_question_id)

    run_results = None
    if submit_action is not None or run_action is not None:
        if not application_question.is_expired():
            answer, created = Answer.objects.update_or_create(application_question=application_question,
                                                              job_question=job_question,
                                                              defaults={"answer": answer_content,
                                                                        "selected_language": selected_language})
        else:
            answer = Answer.objects.filter(application_question=application_question, job_question=job_question).first()

        if run_action is not None:
            executor = FXExecutorFactory.get_executor(selected_language)
            if executor:
                run_results = executor.run_code(answer_content)
            else:
                run_results = {fx_constants.KEY_CODE: fx_constants.KEY_CODE_ERROR,
                               fx_constants.KEY_OUTPUT: 'Language not supported'}
    else:
        job_question_id = int(job_question_id)
        job_questions = get_list_or_404(JobQuestion, job=application_question.job)
        temp_last_id = None
        logging.info('current job q id : ' + str(job_question_id))
        for temp_question in job_questions:
            if prev_action is not None and job_question_id > temp_question.id:
                if temp_last_id is None or temp_question.id > temp_last_id:
                    temp_last_id = temp_question.id
                    job_question = temp_question
            elif next_action is not None and job_question_id < temp_question.id:
                if temp_last_id is None or temp_question.id < temp_last_id:
                    temp_last_id = temp_question.id
                    job_question = temp_question

        logging.info('final job q id : ' + str(job_question_id))
        answer = Answer.objects.filter(application_question=application_question, job_question=job_question).first()

    estimated_end_time = fx_string_utils.format_date_b_d_y_h_m_s(application_question.get_estimated_end_time())
    return render(request, 'job_applications/view_application_questions.html', {'application_question': application_question,
                                                                                 'job_question': job_question,
                                                                                 'interviewee_email': interviewee_email,
                                                                                 'answer': answer,
                                                                                 'run_results': run_results,
                                                                                 'estimated_end_time': estimated_end_time,
                                                                                 'support_languages': fx_constants.SUPPORT_LANGUAGES,
                                                                                 'is_expired': application_question.is_expired()})


def finish_answer(request):
    interviewee_email = request.POST.get('interviewee_email')
    application_question_id = request.POST.get('application_question_id')

    application_question = get_object_or_404(ApplicationQuestion, pk=application_question_id, interviewee_email=interviewee_email)

    if not application_question.is_finished():
        application_question.finish()

    return view_application_questions(request, application_question_id)

job_applications/templates/job_applications/view_application_questions.html
{% extends "main/base.html" %}

{% block title %}Application Questions{% endblock %}

{% block content %}

<div class="page-header">
    <h3>{{ application_question.job.company.name }} - {{ application_question.job.name }}</h3>
    {% if not application_question.is_expired and not application_question.is_finished %}
    <form method="POST" action="{% url 'job_applications:finish_answer' %}">
        {% csrf_token %}
        <input name="interviewee_email" type="hidden" value="{{ interviewee_email }}">
        <input name="application_question_id" type="hidden" value="{{ application_question.id }}">
        <button type="submit" class="btn btn-primary" name="finish_action">Finish</button>
    </form>
    {% endif %}
</div>

<div class="panel panel-default">
    <div class="panel-heading">
         <h3 class="panel-title">{{ job_question.question.name }}</h3>
    </div>
    <div class="panel-body">
        <p>{{ job_question.question.description }}</p>
    </div>
</div>

<form id="application_question_form" method="POST" action="{% url 'job_applications:submit_answer' %}">
    {% csrf_token %}
    <input name="interviewee_email" type="hidden" value="{{ interviewee_email }}">
    <input name="application_question_id" type="hidden" value="{{ application_question.id }}">
    <input name="job_question_id" type="hidden" value="{{ job_question.id }}">
    <input id="answer_content" name="answer_content" type="hidden" value="">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="panel-title">
                        <i class="fa fa-code" aria-hidden="true"></i>
                        <select id="selected_language" name="selected_language">
                        {% if job_question.question.question_type.is_coding_type %}
                            {% for support_language in support_languages %}
                            <option {% if support_language == answer.selected_language %} selected {% endif %} value = {{ support_language }}>
                                {{ support_language }}
                            </option>
                            {% endfor %}
                        {% else%}
                            <option selected value = 'text'>text</option>
                        {% endif %}

                    </select>
                    </h3>
                </div>
                <div id="timer" class="col-md-6 text-right"></div>
            </div>
        </div>

        <div class="panel-body">
            <div id="editor" >{% if answer %}{{ answer.answer }}{% else %}{{ job_question.question.default_template }}{% endif %}</div>
        </div>
    </div>

    {% if job_question.question.question_type.is_coding_type %}
    <div class="panel panel-default">
        <div class="panel-heading">
             <h3 class="panel-title">Output</h3>
        </div>
        <div class="panel-body">
            <p>{{ run_results.output }}</p>
        </div>
    </div>
    {% endif %}

    <div class="btn-group pull-right">
        <div class="btn-group">
            <button type="submit" class="btn btn-primary" name="prev_action" data-toggle="tooltip" title="Previous">
                <i class="fa fa-chevron-left" aria-hidden="true"></i>
            </button>
        </div>

        {% if not application_question.is_expired and not application_question.is_finished %}
        <div class="btn-group">
            <button type="submit" class="btn btn-primary" name="submit_action" data-toggle="tooltip" title="Save">
                <i class="fa fa-floppy-o" aria-hidden="true"></i>
            </button>
        </div>
        {% endif %}

        {% if job_question.question.question_type.is_coding_type %}
        <div class="btn-group">
            <button type="submit" class="btn btn-primary" name="run_action" data-toggle="tooltip" title="Run">
                <i class="fa fa-play" aria-hidden="true"></i>
            </button>
        </div>
        {% endif %}

        <div class="btn-group">
            <button type="submit" class="btn btn-primary" name="next_action" data-toggle="tooltip" title="Next">
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </button>
        </div>
    </div>
</form>

{% load static %}
<script src='{% static "job_applications/ace-builds-master/src-noconflict/ace.js" %}' type="text/javascript" charset="utf-8"></script>
<script src='{% static "job_applications/js/view_application_questions.js" %}' type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href='{% static "job_applications/css/view_application_questions.css" %}' type="text/css" />

<script type="text/javascript" >
    var is_expired = "{{ application_question.is_expired|safe }}";
    var is_finished = "{{ application_question.is_finished|safe }}";
    var estimated_end_time = "{{ estimated_end_time|safe }}";
</script>

{% endblock %}

job_applications/templates/job_applications/welcome.html
{% extends "main/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Application Questions' %}{% endblock %}

{% block content %}

<div class="page-header">
    <h3>{{ application_question.job.company.name }} - {{ application_question.job.name }}</h3>
</div>

<form id="start_application_question_form" method="POST" action="{% url 'job_applications:start_answer' %}">
    {% csrf_token %}
    <input name="interviewee_email" type="hidden" value="{{ interviewee_email }}">
    <input name="application_question_id" type="hidden" value="{{ application_question.id }}">

    <div class="panel panel-default">
        <div class="panel-heading">
             <h3 class="panel-title">{% trans 'Welcome to interview' %}</h3>
        </div>

        <div class="panel-body">
            {% trans 'Once you ready, please click start button.' %}
        </div>
    </div>
    <div class="btn-group btn-group-justified">
        <div class="btn-group"><button type="submit" class="btn btn-primary" name="start_action">{% trans 'Start' %}</button></div>
    </div>
</form>

{% endblock %}